function gui(obj, GUIParent)
%gui is the GUI method for the MIC_MCLMicroDrive class.
% This GUI has several elements which can be used to control a (single
% axis) Mad City Labs micro-drive stage.
%
% INPUTS:
%   GUIParent: The 'Parent' of this GUI, e.g., a figure handle.
%              (Default = figure(...))

% Created by:
%   David J. Schodt (Lidke lab, 2021)


% Create a figure handle for the GUI if needed.
if ~(exist('GUIParent', 'var') && ~isempty(GUIParent) ...
        && isgraphics(GUIParent))
    DefaultFigurePosition = get(0, 'defaultFigurePosition');
    GUIParent = figure('MenuBar', 'none', ...
        'Name', 'MCL micro-drive GUI', 'NumberTitle', 'off', ...
        'Units', 'pixels', ...
        'Position', DefaultFigurePosition .* [1, 1, 0.5, 0.5]);
end

% Add some basic positioning controls.
ButtonPos = [0, 0, 0.15, 0.15];
TextSize = [0, 0, 0.4, 0.1];
EditPos = [0, 0, 0.15, 0.15];
uicontrol(GUIParent, 'Style', 'pushbutton', ...
    'String', '-', 'FontUnits', 'normalized', 'FontSize', 1, ...
    'Units', 'normalized', ...
    'Position', ButtonPos, ...
    'Callback', {@moveDistanceCallback, -1});
uicontrol(GUIParent, 'Style', 'pushbutton', ...
    'String', '+', 'FontUnits', 'normalized', 'FontSize', 1, ...
    'Units', 'normalized', ...
    'Position', ButtonPos + [0, ButtonPos(4), 0, 0], ...
    'Callback', {@moveDistanceCallback, 1});
uicontrol(GUIParent, 'Style', 'text', ...
    'String', 'Step size (mm):', ...
    'FontUnits', 'normalized', 'FontSize', 0.6, ...
    'Units', 'normalized', ...
    'Position', TextSize + [0, 2*ButtonPos(4), 0, 0], ...
    'Callback', {@moveDistanceCallback, 1});
ControlHandles.StepSizeEdit = uicontrol(GUIParent, 'Style', 'edit', ...
    'String', obj.StepSize, 'FontUnits', 'normalized', 'FontSize', 1, ...
    'Units', 'normalized', ...
    'Position', EditPos + [TextSize(3), 2*ButtonPos(4), 0, 0], ...
    'Callback', {@moveDistanceCallback, 1});

    function moveDistanceCallback(~, ~, Direction)
        % Callback for the move distance button.
        Distance = Direction * str2double(ControlHandles.StepSizeEdit);
        obj.moveDistance(Distance)
    end

end