function set_errorcodes(obj)


obj.ErrorCode.DRV_ERROR_CODES=20001;
obj.ErrorCode.DRV_SUCCESS=20002;
obj.ErrorCode.DRV_VXDNOTINSTALLED=20003;
obj.ErrorCode.DRV_ERROR_SCAN=20004;
obj.ErrorCode.DRV_ERROR_CHECK_SUM=20005;
obj.ErrorCode.DRV_ERROR_FILELOAD=20006;
obj.ErrorCode.DRV_UNKNOWN_FUNCTION=20007;
obj.ErrorCode.DRV_ERROR_VXD_INIT=20008;
obj.ErrorCode.DRV_ERROR_ADDRESS=20009;
obj.ErrorCode.DRV_ERROR_PAGELOCK=20010;
obj.ErrorCode.DRV_ERROR_PAGEUNLOCK=20011;
obj.ErrorCode.DRV_ERROR_BOARDTEST=20012;
obj.ErrorCode.DRV_ERROR_ACK=20013;
obj.ErrorCode.DRV_ERROR_UP_FIFO=20014;
obj.ErrorCode.DRV_ERROR_PATTERN=20015;

obj.ErrorCode.DRV_ACQUISITION_ERRORS=20017;
obj.ErrorCode.DRV_ACQ_BUFFER=20018;
obj.ErrorCode.DRV_ACQ_DOWNFIFO_FULL=20019;
obj.ErrorCode.DRV_PROC_UNKONWN_INSTRUCTION=20020;
obj.ErrorCode.DRV_ILLEGAL_OP_CODE=20021;
obj.ErrorCode.DRV_KINETIC_TIME_NOT_MET=20022;
obj.ErrorCode.DRV_ACCUM_TIME_NOT_MET=20023;
obj.ErrorCode.DRV_NO_NEW_DATA=20024;
obj.ErrorCode.DRV_SPOOLERROR=20026;
obj.ErrorCode.DRV_SPOOLSETUPERROR=20027;
obj.ErrorCode.DRV_FILESIZELIMITERROR=20028;

obj.ErrorCode.DRV_TEMPERATURE_CODES=20033;
obj.ErrorCode.DRV_TEMPERATURE_OFF=20034;
obj.ErrorCode.DRV_TEMPERATURE_NOT_STABILIZED=20035;
obj.ErrorCode.DRV_TEMPERATURE_STABILIZED=20036;
obj.ErrorCode.DRV_TEMPERATURE_NOT_REACHED=20037;
obj.ErrorCode.DRV_TEMPERATURE_OUT_RANGE=20038;
obj.ErrorCode.DRV_TEMPERATURE_NOT_SUPPORTED=20039;
obj.ErrorCode.DRV_TEMPERATURE_DRIFT=20040;


obj.ErrorCode.DRV_TEMP_CODES=20033;
obj.ErrorCode.DRV_TEMP_OFF=20034;
obj.ErrorCode.DRV_TEMP_NOT_STABILIZED=20035;
obj.ErrorCode.DRV_TEMP_STABILIZED=20036;
obj.ErrorCode.DRV_TEMP_NOT_REACHED=20037;
obj.ErrorCode.DRV_TEMP_OUT_RANGE=20038;
obj.ErrorCode.DRV_TEMP_NOT_SUPPORTED=20039;
obj.ErrorCode.DRV_TEMP_DRIFT=20040;


obj.ErrorCode.DRV_GENERAL_ERRORS=20049;
obj.ErrorCode.DRV_INVALID_AUX=20050;
obj.ErrorCode.DRV_COF_NOTLOADED=20051;
obj.ErrorCode.DRV_FPGAPROG=20052;
obj.ErrorCode.DRV_FLEXERROR=20053;
obj.ErrorCode.DRV_GPIBERROR=20054;
obj.ErrorCode.DRV_EEPROMVERSIONERROR=20055;

obj.ErrorCode.DRV_DATATYPE=20064;
obj.ErrorCode.DRV_DRIVER_ERRORS=20065;
obj.ErrorCode.DRV_P1INVALID=20066;
obj.ErrorCode.DRV_P2INVALID=20067;
obj.ErrorCode.DRV_P3INVALID=20068;
obj.ErrorCode.DRV_P4INVALID=20069;
obj.ErrorCode.DRV_INIERROR=20070;
obj.ErrorCode.DRV_COFERROR=20071;
obj.ErrorCode.DRV_ACQUIRING=20072;
obj.ErrorCode.DRV_IDLE=20073;
obj.ErrorCode.DRV_TEMPCYCLE=20074;
obj.ErrorCode.DRV_NOT_INITIALIZED=20075;
obj.ErrorCode.DRV_P5INVALID=20076;
obj.ErrorCode.DRV_P6INVALID=20077;
obj.ErrorCode.DRV_INVALID_MODE=20078;
obj.ErrorCode.DRV_INVALID_FILTER=20079;

obj.ErrorCode.DRV_I2CERRORS=20080;
obj.ErrorCode.DRV_I2CDEVNOTFOUND=20081;
obj.ErrorCode.DRV_I2CTIMEOUT=20082;
obj.ErrorCode.DRV_P7INVALID=20083;
obj.ErrorCode.DRV_USBERROR=20089;
obj.ErrorCode.DRV_IOCERROR=20090;
obj.ErrorCode.DRV_VRMVERSIONERROR=20091;
obj.ErrorCode.DRV_USB_INTERRUPT_ENDPOINT_ERROR=20093;
obj.ErrorCode.DRV_RANDOM_TRACK_ERROR=20094;
%% added by qw
obj.ErrorCode.DRV_INVALID_TRIGGER_MODE=20095;
obj.ErrorCode.DRV_LOAD_FIRMWARE_ERROR=20096;
obj.ErrorCode.DRV_DIVIDE_BY_ZERO_ERROR=20097;
obj.ErrorCode.DRV_INVALID_RINGEXPOSURES=20098;
obj.ErrorCode.DRV_BINNING_ERROR=20099;
%%     
obj.ErrorCode.DRV_ERROR_NOCAMERA=20990;
obj.ErrorCode.DRV_NOT_SUPPORTED=20991;
obj.ErrorCode.DRV_NOT_AVAILABLE=20992;

obj.ErrorCode.DRV_ERROR_MAP=20115;
obj.ErrorCode.DRV_ERROR_UNMAP=20116;
obj.ErrorCode.DRV_ERROR_MDL=20117;
obj.ErrorCode.DRV_ERROR_UNMDL=20118;
obj.ErrorCode.DRV_ERROR_BUFFSIZE=20119;
obj.ErrorCode.DRV_ERROR_NOHANDLE=20121;

obj.ErrorCode.DRV_GATING_NOT_AVAILABLE=20130;
obj.ErrorCode.DRV_FPGA_VOLTAGE_ERROR=20131;

obj.ErrorCode.DRV_OW_CMD_FAIL=20150;
obj.ErrorCode.DRV_OWMEMORY_BAD_ADDR=20151;
obj.ErrorCode.DRV_OWCMD_NOT_AVAILABLE=20152;
obj.ErrorCode.DRV_OW_NO_SLAVES=20153;
obj.ErrorCode.DRV_OW_NOT_INITIALIZED=20154;
obj.ErrorCode.DRV_OW_ERROR_SLAVE_NUM=20155;

obj.ErrorCode.AC_ACQMODE_SINGLE=1;
obj.ErrorCode.AC_ACQMODE_VIDEO=2;
obj.ErrorCode.AC_ACQMODE_ACCUMULATE=4;
obj.ErrorCode.AC_ACQMODE_KINETIC=8;
obj.ErrorCode.AC_ACQMODE_FRAMETRANSFER=16;
obj.ErrorCode.AC_ACQMODE_FASTKINETICS=32;

obj.ErrorCode.AC_READMODE_FULLIMAGE=1;
obj.ErrorCode.AC_READMODE_SUBIMAGE=2;
obj.ErrorCode.AC_READMODE_SINGLETRACK=4;
obj.ErrorCode.AC_READMODE_FVB=8;
obj.ErrorCode.AC_READMODE_MULTITRACK=16;
obj.ErrorCode.AC_READMODE_RANDOMTRACK=32;

obj.ErrorCode.AC_TRIGGERMODE_INTERNAL=0;
obj.ErrorCode.AC_TRIGGERMODE_EXTERNAL=1;

obj.ErrorCode.AC_CAMERATYPE_PDA=0;
obj.ErrorCode.AC_CAMERATYPE_IXON=1;
obj.ErrorCode.AC_CAMERATYPE_ICCD=2;
obj.ErrorCode.AC_CAMERATYPE_EMCCD=3;
obj.ErrorCode.AC_CAMERATYPE_CCD=4;
obj.ErrorCode.AC_CAMERATYPE_ISTAR=5;
obj.ErrorCode.AC_CAMERATYPE_VIDEO=6;
obj.ErrorCode.AC_CAMERATYPE_IDUS=7;
obj.ErrorCode.AC_CAMERATYPE_NEWTON=8;
obj.ErrorCode.AC_CAMERATYPE_SURCAM=9;
obj.ErrorCode.AC_CAMERATYPE_USBISTAR=10;
obj.ErrorCode.AC_CAMERATYPE_LUCA=11;

obj.ErrorCode.AC_PIXELMODE_8BIT=1;
obj.ErrorCode.AC_PIXELMODE_14BIT=2;
obj.ErrorCode.AC_PIXELMODE_16BIT=4;
obj.ErrorCode.AC_PIXELMODE_32BIT=8;

obj.ErrorCode.AC_PIXELMODE_MONO=0;
obj.ErrorCode.AC_PIXELMODE_RGB=bitshift(1,16);
obj.ErrorCode.AC_PIXELMODE_CMY=bitshift(2,16);

obj.ErrorCode.AC_SETFUNCTION_VREADOUT=1;
obj.ErrorCode.AC_SETFUNCTION_HREADOUT=2;
obj.ErrorCode.AC_SETFUNCTION_TEMPERATURE=4;
obj.ErrorCode.AC_SETFUNCTION_GAIN=8;
obj.ErrorCode.AC_SETFUNCTION_EMCCDGAIN=16;


%         AC_SETFUNCTION_VREADOUT=1;
%         AC_SETFUNCTION_HREADOUT=2;
%         AC_SETFUNCTION_TEMPERATURE=3;
obj.ErrorCode.AC_SETFUNCTION_MCPGAIN=4; % (AC_SETFUNCTION_GAIN Deprecated)
obj.ErrorCode.AC_SETFUNCTION_EMCCDGAIN=5;
obj.ErrorCode.AC_SETFUNCTION_BASELINECLAMP=6;
obj.ErrorCode.AC_SETFUNCTION_VSAMPLITUDE=7;
obj.ErrorCode.AC_SETFUNCTION_HIGHCAPACITY=8;
obj.ErrorCode.AC_SETFUNCTION_BASELINEOFFSET=9;
obj.ErrorCode.AC_SETFUNCTION_PREAMPGAIN=10;
obj.ErrorCode.AC_SETFUNCTION_CROPMODE=11;
obj.ErrorCode.AC_SETFUNCTION_DMAPARAMETERS=12;
obj.ErrorCode.AC_SETFUNCTION_HORIZONTALBIN=13;
obj.ErrorCode.AC_SETFUNCTION_MULTITRACKHRANGE=14;
obj.ErrorCode.AC_SETFUNCTION_RANDOMTRACKNOGAPS=15;

obj.ErrorCode.AC_GETFUNCTION_TEMPERATURE=1;
obj.ErrorCode.AC_GETFUNCTION_TARGETTEMPERATURE=2;
obj.ErrorCode.AC_GETFUNCTION_TEMPERATURERANGE=4;
obj.ErrorCode.AC_GETFUNCTION_DETECTORSIZE=8;
obj.ErrorCode.AC_GETFUNCTION_GAIN=16;
obj.ErrorCode.AC_GETFUNCTION_EMCCDGAIN=32;

obj.ErrorCode.AC_FEATURES_POLLING=0;
obj.ErrorCode.AC_FEATURES_EVENTS=1;
%obj.ErrorCode.AC_FEATURES_SPOOLING=4;
%obj.ErrorCode.AC_FEATURES_SHUTTER=8;

%         AC_FEATURES_POLLING=1;
%         AC_FEATURES_EVENTS=2;
% SDK documentation on AC_Features contradicts what's in here.
obj.ErrorCode.AC_FEATURES_SPOOLING=2;
obj.ErrorCode.AC_FEATURES_SHUTTER=3;
obj.ErrorCode.AC_FEATURES_SHUTTEREX=4;
obj.ErrorCode.AC_FEATURES_EXTERNAL_I2C=5;
obj.ErrorCode.AC_FEATURES_SATURATIONEVENT=6;
obj.ErrorCode.AC_FEATURES_FANCONTROL=7;
obj.ErrorCode.AC_FEATURES_MIDFANCONTROL=8;
obj.ErrorCode.AC_FEATURES_TEMPERATUREDURINGACQUISITION=9;

obj.ErrorCode.AC_EMGAIN_8BIT=1;
obj.ErrorCode.AC_EMGAIN_12BIT=2;
obj.ErrorCode.AC_EMGAIN_LINEAR12=4;
obj.ErrorCode.AC_EMGAIN_REAL12=8;
